DEVEX-113 - Investigate: SDK on Promise fulfilled first, but the data…
bond-tech/bond-sdk-cards pull request #8
Opened 2021-04-07 13:18 UTC by osylko-bondtech

Investigate: SDK on Promise fulfilled first, but the data takes a few seconds to load
https://bond-financial.atlassian.net/browse/DEVEX-113

**Reason**: Promise is returned when iframe rendered only. But there is async request inside iframe.
**Solution**: Add event listener to subscribe message event. (This approach does not described in the vgs documentation)

2021-04-07 21:48 UTC, dominicsardina requested changes

2021-04-07 21:48 UTC, dominicsardina commented on dist/bond-sdk-cards.js.LICENSE.txt
> +/*!
I never check these in since they're not our licenses.

2021-04-07 21:48 UTC, dominicsardina commented on package.json
> +  "version": "1.4.2",
Your new feature to delay the promise return isn't a bugfix. So I would use 1.5.0

2021-04-07 21:48 UTC, dominicsardina commented on src/bond-sdk-cards.js
> +          if(event.data.messageName === "update" && event.data.payload.revealed === true){
With the inconsistent spacing after "if" it seems like you don't have Prettier formatting your code in your IDE? We'd like all the devs to be consistent and we use Prettier and a customized set of AirBnb's ESLint rules to make sure everyone is doing the same syntax and code-style. Let me know if you'd like help setting those up. There's a confluence page with instructions too.

2021-04-08 17:31 UTC, dominicsardina approved these changes

2021-04-15 12:26 UTC, osylko-bondtech commented
Update documentation SDK regarding to https://bond-financial.atlassian.net/browse/DEVEX-117

https://user-images.githubusercontent.com/78865935/114868743-eee26300-9dfe-11eb-9fe6-b1fede16c242.mov

2021-04-15 19:01 UTC, dominicsardina approved these changes

2021-04-15 20:42 UTC, merged